### ISSUE TITLE
Question: How to view cart contents?

### ISSUE THREAD

**Issue by bomkhati** [seb86/cart-rest-api-for-woocommerce#22]
I was successfull on adding product to cart, but how do we view those cart without loggin in, Does this plugin needs extra setting to view the cart if you are not logged in users. I am getting empty cart. I would be so glad if you can help me out

**Comment by seb86** [comment]
Viewing the carts contents functions the same as you were to view the cart on site. There are no extra parameters.

**See:** https://seb86.github.io/WooCommerce-Cart-REST-API-Docs/#view-cart-contents

 If you are experiencing issues then it maybe to do with your site session, cache or cookies.
