### ISSUE TITLE
syntax error with the function name.

### ISSUE THREAD

**Issue by Mr-AjayM** [seb86/cart-rest-api-for-woocommerce#23]
The plugin code has the syntax error with the function name.

I have installed the latest version of WordPress( 4.9.4  ),  WooCommerce ( 3.3.4 ) and latest version of cart rest api for woocommerce plugin.

When I have clicked on the Activate plugin option of this plugin it gives the syntax error `unexpected include` in WooCommerce-Cart-REST-API\includes\class-wc-cart-rest-api-init.php on line 57

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [X] The issue still exists against the latest `master` branch of WooCommerce Cart REST-API on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup the latest version of WordPress and WooCommerce.
2. Install and activate the latest version of this plugin.

## Expected/actual behavior

When I follow those steps, I see the error as I have described above.

I was expecting to see the plugin activate successfully.

## Isolating the problem

- [X] This bug happens with only WooCommerce Cart REST-API plugin active.
- [X] This bug happens with a default WordPress theme active.
- [X] This bug happens with the latest release of WooCommerce active.
- [X] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
WooCommerce version 3.4.4 does not exist yet @Mr-AjayM Do you mean version 3.3.4?

Also, what are you using to debug as I am not getting this syntax error?

**Comment by Mr-AjayM** [comment]
Sorry, for the inconvenience for the version of the WooCommerce.
Issue faced when just activate the plugin.

**Comment by seb86** [comment]
So you dont have WP debug enabled and it returned with that error when activating, correct?

**Comment by Mr-AjayM** [comment]
yes. Exactly. Please look into this you will found the issue with the code at the link that I have mentioned in the issue.

**Comment by Mr-AjayM** [comment]
I have checked with the PHP version 5.5.12

**Comment by seb86** [comment]
Ah. The minimum PHP requirement is version 5.6

**Comment by seb86** [comment]
I will make that clear in the requirements.

**Comment by Mr-AjayM** [comment]
huhh.... I will update my PHP version and let you know for the same. Please do not close this issue.

**Comment by Mr-AjayM** [comment]
I am able to reproduce this issue in 5.6.25 version of PHP. I have checked also that Keywords can be used as a name in PHP 7 Only. My suggestion is what it should be changed from a keyword.

**Comment by Mr-AjayM** [comment]
And If you are planning to upload on wordpress.org then you have to follow all the coding standard of the WordPress.

**Comment by seb86** [comment]
@Mr-AjayM Thank you for feedback. I will run some tests and make adjustments before submitting to WordPress.org again.
