### ISSUE TITLE
Feedback: What do you think about having saved carts added to the mix?

### ISSUE THREAD

**Issue by seb86** [seb86/cart-rest-api-for-woocommerce#26]
I'm sure many of you are also wanting the ability for customers to save items for later that they have added to the cart but what about saving the whole cart for later.

Amazon does a good job of allowing you to save items for later one item at a time but not the whole cart.
Like most e-commerce sites, Razer does not allow you to save items one at a time but does allow you to save the whole cart to your account.

So I wanted to know your thoughts. Should WooCommerce have this added as part of the core or would it be better as a feature plugin? Should it be item by item, the whole cart or both? Should the customer be able to share their cart publically?

I'm thinking this would not only be a great feature to have but to extend the Cart REST API to support it.

Leave your comments below.

Example of possibly accessing a saved cart: `/wp-json/wc/v2/cart/saved-cart?cart_id=123`

**Comment by MakerManTom** [comment]
This might be answering my question. I'm trying to work out how to navigate through to my Cart built in Postman in my web browser?

Otherwise, multiple carts would be really handy for my use case.

Great work on this BTW!
