### ISSUE TITLE
'validate_callback' 'is_numeric' arguments for Add Item rest route causes Fatal Error

### ISSUE THREAD

**Issue by 21stcn** [seb86/cart-rest-api-for-woocommerce#30]
Using the php WooCommerce rest api library, I was getting a fatal error when adding items to cart:

```
$data = [
   "product_id" => 234,
   "quantity" => 1
];

$woocommerce->post('cart/add', $data);
```

`Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'unexpected character' in .../wc-api-php/WooCommerce/HttpClient/HttpClient.php`

This fatal error was being caused because a warning was being thrown

`Warning: is_numeric() expects exactly 1 parameter, 3 given in .../wp-includes/rest-api/class-wp-rest-request.php on line 858`

which caused the callback function to be called with invalid data.

The issue is naming the 'is_numeric' function as the 'validate_callback' for integers arguments set for the rest route for Add Item in class-wc-rest-cart-controller.php :

```
'args'     => array(
   'product_id' => array(
	'validate_callback' => 'is_numeric'
   ),
   'quantity' => array(
	'validate_callback' => 'is_numeric'
   ),
   'variation_id' => array(
	'validate_callback' => 'is_numeric'
   ),
```

This exact issue is described in the Custom Endpoint docs for the Wordpress Rest API in the Arguments section: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

> You could also pass in a function name to validate_callback, but passing certain functions like is_numeric directly will not only throw a warning about having extra parameters passed to it, but will also return NULL causing the callback function to be called with invalid data. We hope to eventually solve this problem in WordPress core.

The problem seems to be solved by using their example format, as opposed to naming the 'is_numeric' function: 

```
'args' => array(
      'id' => array(
        'validate_callback' => function($param, $request, $key) {
          return is_numeric( $param );
        }
      ),
```

**Comment by seb86** [comment]
OK @21stcn Thank you for issuing the report. If you are able to put in a pull request with the correction I will merge it ready for next release.

**Comment by seb86** [comment]
Fixed.
