### ISSUE TITLE
Completely broken with wp-api-php library

### ISSUE THREAD

**Issue by 21stcn** [seb86/cart-rest-api-for-woocommerce#31]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Cart REST-API for WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Install wordpress
2. Install woocommerce
3. Enable rest api and get key and secret
4. Install cart rest api for woocommerce
5. Install woocommerce api php client https://github.com/woocommerce/wc-api-php
6. Add item to cart logged in as admin user
7. add print_r($woocommerce->get('cart')); to header.php file
8. visit site from another device
9. can see contents of cart printed

## Expected/actual behaviour

After developing extensively relying on this plugin, I eventually got to testing with a different user/browser/device and realised the plugin was always interacting with the same cart. It's easy to see the problem, just go to the test site I set up https://bight.pillbox.co.za/ . You will see the result of 

```
global $woocommerce;
print_r($woocommerce->get('cart'));
```

there (which is in storefront header.php). How is it possible that a cart is being fetched there? You have never visited the site and are not logged in. The test site is a clean wordpress and woocommerce with no extra plugins.

I expect that $woocommerce->get('cart') and all other cart related api functions in the cart plugin would interact with the cart of the logged in user/current session, only but they seem to just interact with the cart of the admin/first user. Same with the post functions etc.

Essentially the cart rest api calls are always interacting with a single cart which has nothing to do with the current user/session.

Am I missing something basic here or does the 'php' aspect of the cart api plugin not work with WooCommerce API - PHP Client?

Aside from installing woocommerce and cart rest api plugin, the only other changes I have made are to include the WooCommerce API - PHP Client like so (might making $woocommerce global have something to do with it?):

Contents of wc-api-init:

```
require __DIR__ . '/WooCommerce/Client.php';
require __DIR__ . '/WooCommerce/HttpClient/BasicAuth.php';
require __DIR__ . '/WooCommerce/HttpClient/HttpClient.php';
require __DIR__ . '/WooCommerce/HttpClient/HttpClientException.php';
require __DIR__ . '/WooCommerce/HttpClient/OAuth.php';
require __DIR__ . '/WooCommerce/HttpClient/Options.php';
require __DIR__ . '/WooCommerce/HttpClient/Request.php';
require __DIR__ . '/WooCommerce/HttpClient/Response.php';

use Automattic\WooCommerce\Client;

global $woocommerce;
$woocommerce = new Client(
    'http://bight.pillbox.co.za', 
    'ck_c8a3ef5088180731901999f8faf07fccd2b4591a', 
    'cs_0560ac9c15e743f4c172159da8a0d949da97a059',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);
```

Contents of header.php

```
	<div id="content" class="site-content" tabindex="-1">
		<div class="col-full">

		<?php
		do_action( 'storefront_content_top' );

		global $woocommerce;
		print_r($woocommerce->get('cart'));
```

(If you want I can give you access to this install.)

## Isolating the problem

- [x] This bug happens with only WooCommerce and Cart REST-API for WooCommerce plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://bight.pillbox.co.za
Site URL: https://bight.pillbox.co.za
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.33-0+deb8u1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.35-MariaDB-1~jessie
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.89MB
Database Data Size: 1.05MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.41MB + Index: 0.02MB
wp_postmeta: Data: 0.09MB + Index: 0.03MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 8
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Cart REST API for WooCommerce: by Sébastien Dumont – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.6
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by seb86** [comment]
Hi @21stcn 

It should be loading from session when the user is logged out but I think because you have set the consumer key and secret that it thinks you are logged in constantly. The cart endpoint does not require these.

Try removing them and see if it makes a difference.

**Comment by 21stcn** [comment]
Thanks for your response. 

The docs for the cart plugin recommend using the 'WooCommerce API - PHP Client' and the key and secret are required to use that library: https://github.com/woocommerce/wc-api-php

Is there an easy way to use your plugin with php without using that library, or without using the key and secret? For example, to get the contents of the cart without the above php wrapper library? Can you perhaps suggest a way to get your plugin working with php as per the docs?

(I tried curl but the session is not preserved so even if there are items in the cart, it says 'cart is empty'.

Javascript does not work either as session/cookie data is not transmitted, so I cannot get the cart except from the initialised shop site. The point of using the rest api for me is to get the cart from another site in the multisite. )

**Comment by seb86** [comment]
If you are only using the library for the cart then I would suggest forking the library and remove the required consumer key and secret and use your modified version instead.

That is the only quick solution I can provide at this time.

**Comment by 21stcn** [comment]
Ok, I might consider it down the line. For now I think I'll just create orders using the rest api and skip the cart as I'm pushing a deadline.

Maybe update the docs for your plugin, if you get the opportunity, if it is indeed the case that it does not work out the box with the woocommerce rest api php wrapper library, as advertised. 

Thanks for your assistance and time. Hopefully this plugin can mature and become a standard companion to the WC rest api.

**Comment by seb86** [comment]
As my Cart REST API is not official I don't see WooCommerce making exceptions or adding Cart support in the coming REST API version but I will update the documentation when I get the chance. Thank you for testing and reporting back to me with your feedback.
